[package]
name = "trie-complete-rs"
version = "0.1.0"
authors = ["Egoist"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
